services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    DigipolisGent\SettingBundle\FieldType\StringFieldType:
        tags:
            - { name: field_type}
    DigipolisGent\SettingBundle\FieldType\BooleanFieldType:
        tags:
            - { name: field_type}
    DigipolisGent\SettingBundle\Service\FieldTypeServiceCollector:
    DigipolisGent\SettingBundle\EventListener\DynamicSettingImplementationRelationSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }
    DigipolisGent\SettingBundle\Form\Type\ConfigFormType:
        tags:
            - { name: form.type}
    DigipolisGent\SettingBundle\Service\FormService:
    DigipolisGent\SettingBundle\Service\EntityTypeCollector:
    DigipolisGent\SettingBundle\Service\DataTypeCollector: